//
// Autogenerated by Laurine - by Jiri Trecak ( http://jiritrecak.com, @jiritrecak )
// Do not change this file manually!
//


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Imports

import Foundation


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Localizations


public struct Localizations {

    /// Base translation: Email Logs
    public static var EmailLogs : String = NSLocalizedString("EmailLogs", comment: "")

    /// Base translation: There was an error adding this issuer. This can happen when a single-use invitation link is clicked more than once. Please check with the issuer and request a new invitation, if necessary.
    public static var AddIssuerFailMessage : String = NSLocalizedString("AddIssuerFailMessage", comment: "")

    /// Base translation: Adding Issuer
    public static var AddingIssuer : String = NSLocalizedString("AddingIssuer", comment: "")

    /// Base translation: Okay
    public static var Okay : String = NSLocalizedString("Okay", comment: "")

    /// Base translation: Enter
    public static var Enter : String = NSLocalizedString("Enter", comment: "")

    /// Base translation: View
    public static var View : String = NSLocalizedString("View", comment: "")

    /// Base translation: Date Issued
    public static var DateIssued : String = NSLocalizedString("DateIssued", comment: "")

    /// Base translation: Ready!
    public static var NewUserHeader : String = NSLocalizedString("NewUserHeader", comment: "")

    /// Base translation: Privacy Policy
    public static var PrivacyPolicy : String = NSLocalizedString("PrivacyPolicy", comment: "")

    /// Base translation: No Network Connection
    public static var ReachabilityAlertTitle : String = NSLocalizedString("ReachabilityAlertTitle", comment: "")

    /// Base translation: Log out and Reset
    public static var LoginToIssuer : String = NSLocalizedString("LoginToIssuer", comment: "")

    /// Base translation: Enter the URL provided by the issuer
    public static var EnterIssuerURL : String = NSLocalizedString("EnterIssuerURL", comment: "")

    /// Base translation: Issuers
    public static var Issuers : String = NSLocalizedString("Issuers", comment: "")

    /// Base translation: Tap continue to begin.
    public static var UpdateUserBody3 : String = NSLocalizedString("UpdateUserBody3", comment: "")

    /// Base translation: Select Backup Methods
    public static var SelectBackupMethods : String = NSLocalizedString("SelectBackupMethods", comment: "")

    /// Base translation: Blockcerts Backup
    public static var BlockcertsBackup : String = NSLocalizedString("BlockcertsBackup", comment: "")

    /// Base translation: Enter the one-time code
    public static var EnterIssuerCode : String = NSLocalizedString("EnterIssuerCode", comment: "")

    /// Base translation: Play intro video.
    public static var PlayIntroVideo : String = NSLocalizedString("PlayIntroVideo", comment: "")

    /// Base translation: Show Passphrase
    public static var ShowPassphrase : String = NSLocalizedString("ShowPassphrase", comment: "")

    /// Base translation: Write your passphrase on a piece of paper and store it in a secure location.
    public static var WriteYourPassphrase : String = NSLocalizedString("WriteYourPassphrase", comment: "")

    /// Base translation: Close
    public static var Close : String = NSLocalizedString("Close", comment: "")

    /// Base translation: My Passphrase
    public static var MyPassphrase : String = NSLocalizedString("MyPassphrase", comment: "")

    /// Base translation: The request was aborted. Please try again.
    public static var RequestAborted : String = NSLocalizedString("RequestAborted", comment: "")

    /// Base translation: Authenticate to see your secure passphrase.
    public static var AuthenticateSeePassphrase : String = NSLocalizedString("AuthenticateSeePassphrase", comment: "")

    /// Base translation: The server encountered an error. Please try again.
    public static var ServerError : String = NSLocalizedString("ServerError", comment: "")

    /// Base translation: Share Link
    public static var ShareLink : String = NSLocalizedString("ShareLink", comment: "")

    /// Base translation: Caution!
    public static var Caution : String = NSLocalizedString("Caution", comment: "")

    /// Base translation: The app is in an invalid state. Please quit the app & relaunch. Then try again.
    public static var AppRestartRequired : String = NSLocalizedString("AppRestartRequired", comment: "")

    /// Base translation: No description provided.
    public static var IssuerMissingDescription : String = NSLocalizedString("IssuerMissingDescription", comment: "")

    /// Base translation: We couldn't understand this Issuer's response. Please contact the Issuer.
    public static var IssuerResponseErrorJSON : String = NSLocalizedString("IssuerResponseErrorJSON", comment: "")

    /// Base translation: Manual Hard Copy
    public static var ManualHardCopy : String = NSLocalizedString("ManualHardCopy", comment: "")

    /// Base translation: Replace Passphrase
    public static var ReplacePassphrase : String = NSLocalizedString("ReplacePassphrase", comment: "")

    /// Base translation: Something went wrong preparing that file for sharing. Try again later.
    public static var ShareCredentialGenericError : String = NSLocalizedString("ShareCredentialGenericError", comment: "")

    /// Base translation: Parse issuer keys
    public static var OneTimeCode : String = NSLocalizedString("OneTimeCode", comment: "")

    /// Base translation: Something went wrong adding this issuer. Try again later.
    public static var AddIssuerGenericError : String = NSLocalizedString("AddIssuerGenericError", comment: "")

    /// Base translation: Cancel
    public static var Cancel : String = NSLocalizedString("Cancel", comment: "")

    /// Base translation: Invalid Passphrase
    public static var InvalidPassphrase : String = NSLocalizedString("InvalidPassphrase", comment: "")

    /// Base translation: 1 Credential
    public static var OneCredential : String = NSLocalizedString("OneCredential", comment: "")

    /// Base translation: Missing Issuer
    public static var MissingIssuer : String = NSLocalizedString("MissingIssuer", comment: "")

    /// Base translation: This credential is not verified. Please contact the issuer.
    public static var VerificationFail : String = NSLocalizedString("VerificationFail", comment: "")

    /// Base translation: New User
    public static var NewUser : String = NSLocalizedString("NewUser", comment: "")

    /// Base translation: Passphrase
    public static var Passphrase : String = NSLocalizedString("Passphrase", comment: "")

    /// Base translation: Continue
    public static var Continue : String = NSLocalizedString("Continue", comment: "")

    /// Base translation: In order to add this issuer, you must have the latest version of Blockerts Wallet.
    public static var AppUpdateAlertMessage : String = NSLocalizedString("AppUpdateAlertMessage", comment: "")

    /// Base translation: This credential was successfully imported. It can be found in the issuer view.
    public static var CredentialImportSuccess : String = NSLocalizedString("CredentialImportSuccess", comment: "")

    /// Base translation: Protect Your Passphrase
    public static var ProtectYourPassphrase : String = NSLocalizedString("ProtectYourPassphrase", comment: "")

    /// Base translation: URL
    public static var URL : String = NSLocalizedString("URL", comment: "")

    /// Base translation: Information
    public static var Information : String = NSLocalizedString("Information", comment: "")

    /// Base translation: Unable to save this passphrase.
    public static var PassphraseSaveFail : String = NSLocalizedString("PassphraseSaveFail", comment: "")

    /// Base translation: Share This Credential
    public static var ShareCredential : String = NSLocalizedString("ShareCredential", comment: "")

    /// Base translation: Issuer responded, but didn't include the "%@" property
    public static func IssuerMissingProperty(_ value1 : String) -> String {
        return String(format: NSLocalizedString("IssuerMissingProperty", comment: ""), value1)
    }

    /// Base translation: Add Issuer Failed
    public static var AddIssuerFailAlertTitle : String = NSLocalizedString("AddIssuerFailAlertTitle", comment: "")

    /// Base translation: Failed to authenticate. Try again.
    public static var AuthenticationError : String = NSLocalizedString("AuthenticationError", comment: "")

    /// Base translation: Invalid Credential
    public static var InvalidCredential : String = NSLocalizedString("InvalidCredential", comment: "")

    /// Base translation: Okay
    public static var OK : String = NSLocalizedString("OK", comment: "")

    /// Base translation: Issuer Contact Email
    public static var IssuerContactEmail : String = NSLocalizedString("IssuerContactEmail", comment: "")

    /// Base translation: This doesn't appear to be a valid credential URL. Please check it and try again.
    public static var InvalidCredentialFile : String = NSLocalizedString("InvalidCredentialFile", comment: "")

    /// Base translation: Blockcerts Wallet
    public static var BlockcertsWallet : String = NSLocalizedString("BlockcertsWallet", comment: "")

    /// Base translation: You may add an issuer manually by visiting Settings and tapping Add an Issuer.
    public static var NewUserFooter : String = NSLocalizedString("NewUserFooter", comment: "")

    /// Base translation: You will receive an email when a credential is issued. Follow the link in the email to complete the process.
    public static var EmptyCredentials : String = NSLocalizedString("EmptyCredentials", comment: "")

    /// Base translation: Settings
    public static var Settings : String = NSLocalizedString("Settings", comment: "")

    /// Base translation: Credential Name
    public static var CredentialName : String = NSLocalizedString("CredentialName", comment: "")

    /// Base translation: No Credentials
    public static var NoCredentials : String = NSLocalizedString("NoCredentials", comment: "")

    /// Base translation: Introduced on
    public static var IntroducedOn : String = NSLocalizedString("IntroducedOn", comment: "")

    /// Base translation: We couldn't find the logs on the device.
    public static var DeviceMissingLogs : String = NSLocalizedString("DeviceMissingLogs", comment: "")

    /// Base translation: Please check your network connection and try again.
    public static var ReachabilityAlertMessage : String = NSLocalizedString("ReachabilityAlertMessage", comment: "")

    /// Base translation: Never
    public static var Never : String = NSLocalizedString("Never", comment: "")

    /// Base translation: This is the passphrase to your wallet. There is a backup on this phone, but you must create an extra one in case you switch devices.
    public static var PassphraseDescription : String = NSLocalizedString("PassphraseDescription", comment: "")

    /// Base translation: Credential URL
    public static var CredentialURL : String = NSLocalizedString("CredentialURL", comment: "")

    /// Base translation: Please check it and try again.
    public static var CheckPassphraseTryAgain : String = NSLocalizedString("CheckPassphraseTryAgain", comment: "")

    /// Base translation: You've already imported that file. Want to view it?
    public static var FileAlreadyImportedExplanation : String = NSLocalizedString("FileAlreadyImportedExplanation", comment: "")

    /// Base translation: Couldn't delete file
    public static var DeleteFileError : String = NSLocalizedString("DeleteFileError", comment: "")

    /// Base translation: Take ownership of your digital records
    public static var Success : String = NSLocalizedString("Success", comment: "")

    /// Base translation: Something went wrong when deleting that certificate.
    public static var DeleteCredentialGenericError : String = NSLocalizedString("DeleteCredentialGenericError", comment: "")

    /// Base translation: Please Update Blockcerts Wallet
    public static var AppUpdateAlertTitle : String = NSLocalizedString("AppUpdateAlertTitle", comment: "")

    /// Base translation: Delete Credential
    public static var DeleteCredential : String = NSLocalizedString("DeleteCredential", comment: "")

    /// Base translation: Replace
    public static var Replace : String = NSLocalizedString("Replace", comment: "")

    /// Base translation: Description
    public static var Description : String = NSLocalizedString("Description", comment: "")

    /// Base translation: Please note that you are now required to back up your passphrase, but you can do so easily in the app.
    public static var UpdateUserBody2 : String = NSLocalizedString("UpdateUserBody2", comment: "")

    /// Base translation: You have %@ credentials
    public static func MultipleCredentials(_ value1 : String) -> String {
        return String(format: NSLocalizedString("MultipleCredentials", comment: ""), value1)
    }

    /// Base translation: To see your issuers, go to Settings to add your credentials or add them via the email from the Issuer.
    public static var ReturningUserBody : String = NSLocalizedString("ReturningUserBody", comment: "")

    /// Base translation: Logs have been deleted from this device.
    public static var DeleteLogsSuccess : String = NSLocalizedString("DeleteLogsSuccess", comment: "")

    /// Base translation: Couldn't read file
    public static var ReadFileError : String = NSLocalizedString("ReadFileError", comment: "")

    /// Base translation: You will receive an email when an issuer is ready to be added. Follow the link in the email to complete the process.
    public static var NewUserBody : String = NSLocalizedString("NewUserBody", comment: "")

    /// Base translation: You have 1 credential
    public static var YouHaveOneCredential : String = NSLocalizedString("YouHaveOneCredential", comment: "")

    /// Base translation: This is a low-security backup method. Do you want to continue?
    public static var EmailBackupWarning : String = NSLocalizedString("EmailBackupWarning", comment: "")

    /// Base translation: Select At Least One to Continue
    public static var SelectOneButton : String = NSLocalizedString("SelectOneButton", comment: "")

    /// Base translation: Are You Sure?
    public static var AreYouSure : String = NSLocalizedString("AreYouSure", comment: "")

    /// Base translation: Share File
    public static var ShareFile : String = NSLocalizedString("ShareFile", comment: "")

    /// Base translation: Create Backup
    public static var CreateBackup : String = NSLocalizedString("CreateBackup", comment: "")

    /// Base translation: Re-import Your Credentials
    public static var ReturningUserHeader : String = NSLocalizedString("ReturningUserHeader", comment: "")

    /// Base translation: Import Complete
    public static var ImportComplete : String = NSLocalizedString("ImportComplete", comment: "")

    /// Base translation: Issuer
    public static var Issuer : String = NSLocalizedString("Issuer", comment: "")

    /// Base translation: Please type or paste the credential URL:
    public static var CopyCredentialURL : String = NSLocalizedString("CopyCredentialURL", comment: "")

    /// Base translation: File already imported
    public static var FileAlreadyImported : String = NSLocalizedString("FileAlreadyImported", comment: "")

    /// Base translation: Passphrase Generated!
    public static var PassphraseGenerated : String = NSLocalizedString("PassphraseGenerated", comment: "")

    /// Base translation: Issuer responded, but it contained an invalid property named "%@"
    public static func IssuerInvalidProperty(_ value1 : String) -> String {
        return String(format: NSLocalizedString("IssuerInvalidProperty", comment: ""), value1)
    }

    /// Base translation: We couldn't authenticate you to the issuer. Double-check your one-time code and try again.
    public static var IssuerAuthenticationError : String = NSLocalizedString("IssuerAuthenticationError", comment: "")

    /// Base translation: Backup Passphrase
    public static var BackupPassphrase : String = NSLocalizedString("BackupPassphrase", comment: "")

    /// Base translation: Credential
    public static var Credential : String = NSLocalizedString("Credential", comment: "")

    /// Base translation: Delete
    public static var Delete : String = NSLocalizedString("Delete", comment: "")

    /// Base translation: You have %@ credentials
    public static func YouHaveMultipleCredentials(_ value1 : String) -> String {
        return String(format: NSLocalizedString("YouHaveMultipleCredentials", comment: ""), value1)
    }

    /// Base translation: Verify
    public static var Verify : String = NSLocalizedString("Verify", comment: "")

    /// Base translation: Issuer URL
    public static var IssuerURL : String = NSLocalizedString("IssuerURL", comment: "")

    /// Base translation: Add Credential
    public static var AddCredential : String = NSLocalizedString("AddCredential", comment: "")

    /// Base translation: Share
    public static var Share : String = NSLocalizedString("Share", comment: "")

    /// Base translation: Credential Expiration
    public static var CredentialExpiration : String = NSLocalizedString("CredentialExpiration", comment: "")

    /// Base translation: Copy to Email or Clipboard
    public static var CopyEmailClipboard : String = NSLocalizedString("CopyEmailClipboard", comment: "")

    /// Base translation: Current User
    public static var CurrentUser : String = NSLocalizedString("CurrentUser", comment: "")

    /// Base translation: Import from File
    public static var ImportFromFile : String = NSLocalizedString("ImportFromFile", comment: "")

    /// Base translation: This issuer appears to have been tampered with. Please contact the issuer.
    public static var IssuerTampered : String = NSLocalizedString("IssuerTampered", comment: "")

    /// Base translation: Enter Passphrase
    public static var EnterPassphrase : String = NSLocalizedString("EnterPassphrase", comment: "")

    /// Base translation: Current Passphrase
    public static var CurrentPassphrase : String = NSLocalizedString("CurrentPassphrase", comment: "")

    /// Base translation: Done
    public static var Done : String = NSLocalizedString("Done", comment: "")

    /// Base translation: Choose a method:
    public static var ChooseMethod : String = NSLocalizedString("ChooseMethod", comment: "")

    /// Base translation: This is a valid %@ credential.
    public static func VerificationSuccess(_ value1 : String) -> String {
        return String(format: NSLocalizedString("VerificationSuccess", comment: ""), value1)
    }

    /// Base translation: You may add an issuer manually by visiting Settings and tapping Add an Issuer.
    public static var ReturningUserFooter : String = NSLocalizedString("ReturningUserFooter", comment: "")

    /// Base translation: About Passphrases
    public static var AboutPassphrases : String = NSLocalizedString("AboutPassphrases", comment: "")

    /// Base translation: Credential Info
    public static var CredentialInfo : String = NSLocalizedString("CredentialInfo", comment: "")

    /// Base translation: Play intro video.
    public static var PlayButtonAccessibility : String = NSLocalizedString("PlayButtonAccessibility", comment: "")

    /// Base translation: Please select at least one option below:
    public static var SelectOne : String = NSLocalizedString("SelectOne", comment: "")

    /// Base translation: Adding this issuer failed. Please try again
    public static var AddIssuerFailAlertMessage : String = NSLocalizedString("AddIssuerFailAlertMessage", comment: "")

    /// Base translation: Please type or paste your passphrase here:
    public static var EnterPassphraseInstruction : String = NSLocalizedString("EnterPassphraseInstruction", comment: "")

    /// Base translation: Something went wrong when trying to open the file.
    public static var CredentialParseError : String = NSLocalizedString("CredentialParseError", comment: "")

    /// Base translation: Issuer Name
    public static var IssuerName : String = NSLocalizedString("IssuerName", comment: "")

    /// Base translation: Verified!
    public static var Verified : String = NSLocalizedString("Verified", comment: "")

    /// Base translation: Authenticate to replace your secure passphrase.
    public static var AuthenticateReplacePassphrase : String = NSLocalizedString("AuthenticateReplacePassphrase", comment: "")

    /// Base translation: Import from URL
    public static var ImportFromURL : String = NSLocalizedString("ImportFromURL", comment: "")

    /// Base translation: Import
    public static var Import : String = NSLocalizedString("Import", comment: "")

    /// Base translation: We've improved the experience, but you'll be able to receive and manage your credentials as before. Please note that you are now required to back up your passphrase, but you can do so easily in the app. Tap continue to begin.
    public static var UpdateUserBody : String = NSLocalizedString("UpdateUserBody", comment: "")

    /// Base translation: Verification
    public static var Verification : String = NSLocalizedString("Verification", comment: "")

    /// Base translation: Shared Address
    public static var SharedAddress : String = NSLocalizedString("SharedAddress", comment: "")

    /// Base translation: Welcome
    public static var Welcome : String = NSLocalizedString("Welcome", comment: "")

    /// Base translation: Adding Credential
    public static var AddingCredential : String = NSLocalizedString("AddingCredential", comment: "")

    /// Base translation: Verifying %@ Credential...
    public static func VerificationInProgress(_ value1 : String) -> String {
        return String(format: NSLocalizedString("VerificationInProgress", comment: ""), value1)
    }

    /// Base translation: Info
    public static var Info : String = NSLocalizedString("Info", comment: "")

    /// Base translation: Couldn't share certificate.
    public static var ShareCredentialError : String = NSLocalizedString("ShareCredentialError", comment: "")

    /// Base translation: This is a sample certificate that cannot be verified. Real certificates will perform a live validation process.
    public static var SampleCredentialVerificationImpossible : String = NSLocalizedString("SampleCredentialVerificationImpossible", comment: "")

    /// Base translation: About Passphrase
    public static var AboutPassphrase : String = NSLocalizedString("AboutPassphrase", comment: "")

    /// Base translation: Add Issuer
    public static var AddIssuer : String = NSLocalizedString("AddIssuer", comment: "")

    /// Base translation: Sample Certificate
    public static var SampleCredential : String = NSLocalizedString("SampleCredential", comment: "")

    /// Base translation: File not found
    public static var FileNotFound : String = NSLocalizedString("FileNotFound", comment: "")

    /// Base translation: If you delete this credential and don't have a backup, you'll have to ask the issuer to send it again if you want to recover it.   Are you sure you want to delete this credential?
    public static var DeleteCredentialExplanation : String = NSLocalizedString("DeleteCredentialExplanation", comment: "")

    /// Base translation: It looks like local authentication is disabled for this app. Without it, showing your passphrase is insecure. Please enable local authentication for this app in Settings.
    public static var LocalAuthenticationDisabled : String = NSLocalizedString("LocalAuthenticationDisabled", comment: "")

    /// Base translation: Please go to the Settings for Blockcerts Wallet and enable Touch ID, Face ID, or a passcode to secure your passphrase and try again.
    public static var EnableAuthenticationPrompt : String = NSLocalizedString("EnableAuthenticationPrompt", comment: "")

    /// Base translation: Please try to authenticate again to see your passphrase.
    public static var GenericAuthenticationError : String = NSLocalizedString("GenericAuthenticationError", comment: "")

    /// Base translation: Issuer Info
    public static var IssuerInfo : String = NSLocalizedString("IssuerInfo", comment: "")

    /// Base translation: Welcome to the new Blockcerts Wallet!
    public static var UpdateUserHeader : String = NSLocalizedString("UpdateUserHeader", comment: "")

    /// Base translation: An issuer was added. Please check your issuers screen.
    public static var AddIssuerSuccess : String = NSLocalizedString("AddIssuerSuccess", comment: "")

}
