//
// Autogenerated by Laurine - by Jiri Trecak ( http://jiritrecak.com, @jiritrecak )
// Do not change this file manually!
//


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Imports

import Foundation


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Localizations


public struct Localizations {

    /// Base translation: Replace
    public static var Replace : String = NSLocalizedString("Replace", comment: "")

    /// Base translation: View
    public static var View : String = NSLocalizedString("View", comment: "")

    /// Base translation: Import from File
    public static var ImportFromFile : String = NSLocalizedString("ImportFromFile", comment: "")

    /// Base translation: [Old Version]
    public static var AppUpdateAlertTitle : String = NSLocalizedString("AppUpdateAlertTitle", comment: "")

    /// Base translation: You've already imported that file. Want to view it?
    public static var FileAlreadyImported : String = NSLocalizedString("FileAlreadyImported", comment: "")

    /// Base translation: Something went wrong adding this issuer. Try again later.
    public static var AddIssuerGenericError : String = NSLocalizedString("AddIssuerGenericError", comment: "")

    /// Base translation: The app is in an invalid state. Please quit the app & relaunch. Then try again.
    public static var AppRestartRequired : String = NSLocalizedString("AppRestartRequired", comment: "")

    /// Base translation: Are you sure?
    public static var AreYouSure : String = NSLocalizedString("AreYouSure", comment: "")

    /// Base translation: An issuer was added. Please check your issuers screen.
    public static var AddIssuerSuccess : String = NSLocalizedString("AddIssuerSuccess", comment: "")

    /// Base translation: Authenticate to replace your secure passphrase.
    public static var AuthenticateReplacePassphrase : String = NSLocalizedString("AuthenticateReplacePassphrase", comment: "")

    /// Base translation: Passphrase invalid
    public static var PassphraseInvalid : String = NSLocalizedString("PassphraseInvalid", comment: "")

    /// Base translation: [Lorem ipsum latin for go to App Store]
    public static var AppUpdateAlertMessage : String = NSLocalizedString("AppUpdateAlertMessage", comment: "")

    /// Base translation: That file doesn't appear to be a valid credential.
    public static var InvalidCredentialFile : String = NSLocalizedString("InvalidCredentialFile", comment: "")

    /// Base translation: This isn't a valid passphrase. Check what you entered and try again.
    public static var InvalidPassphrase : String = NSLocalizedString("InvalidPassphrase", comment: "")

    /// Base translation: Sample Certificate
    public static var SampleCredential : String = NSLocalizedString("SampleCredential", comment: "")

    /// Base translation: A credential was imported. Please check your credentials screen.
    public static var CredentialImportSuccess : String = NSLocalizedString("CredentialImportSuccess", comment: "")

    /// Base translation: Description
    public static var Description : String = NSLocalizedString("Description", comment: "")

    /// Base translation: Settings
    public static var Settings : String = NSLocalizedString("Settings", comment: "")

    /// Base translation: New User
    public static var NewUser : String = NSLocalizedString("NewUser", comment: "")

    /// Base translation: Couldn't delete file
    public static var DeleteFileError : String = NSLocalizedString("DeleteFileError", comment: "")

    /// Base translation: Email Logs
    public static var EmailLogs : String = NSLocalizedString("EmailLogs", comment: "")

    /// Base translation: Missing Issuer
    public static var MissingIssuer : String = NSLocalizedString("MissingIssuer", comment: "")

    /// Base translation: The server encountered an error. Please try again.
    public static var ServorError : String = NSLocalizedString("ServorError", comment: "")

    /// Base translation: URL
    public static var URL : String = NSLocalizedString("URL", comment: "")

    /// Base translation: Couldn't read file
    public static var ReadFileError : String = NSLocalizedString("ReadFileError", comment: "")

    /// Base translation: Add a Credential
    public static var AddACredential : String = NSLocalizedString("AddACredential", comment: "")

    /// Base translation: File not found
    public static var FileNotFound : String = NSLocalizedString("FileNotFound", comment: "")

    /// Base translation: If you delete this certificate and don't have a backup, then you'll have to ask the issuer to send it to you again if you want to recover it. Are you sure you want to delete this certificate?
    public static var DeleteCredentialExplanation : String = NSLocalizedString("DeleteCredentialExplanation", comment: "")

    /// Base translation: Passphrase
    public static var Passphrase : String = NSLocalizedString("Passphrase", comment: "")

    /// Base translation: Please check your passphrase and try again.
    public static var CheckPassphrase : String = NSLocalizedString("CheckPassphrase", comment: "")

    /// Base translation: Share File
    public static var ShareFile : String = NSLocalizedString("ShareFile", comment: "")

    /// Base translation: About Passphrase
    public static var AboutPassphrase : String = NSLocalizedString("AboutPassphrase", comment: "")

    /// Base translation: Something went wrong when trying to open the file.
    public static var CredentialParseError : String = NSLocalizedString("CredentialParseError", comment: "")

    /// Base translation: My Passphrase
    public static var MyPassphrase : String = NSLocalizedString("MyPassphrase", comment: "")

    /// Base translation: This issuer appears to have been tampered with. Please contact the issuer.
    public static var IssuerTampered : String = NSLocalizedString("IssuerTampered", comment: "")

    /// Base translation: Shared Address
    public static var SharedAddress : String = NSLocalizedString("SharedAddress", comment: "")

    /// Base translation: Credential Expiration
    public static var CredentialExpiration : String = NSLocalizedString("CredentialExpiration", comment: "")

    /// Base translation: Issuer responded, but didn't include the "%@" property
    public static func IssuerMissingProperty(_ value1 : String) -> String {
        return String(format: NSLocalizedString("IssuerMissingProperty", comment: ""), value1)
    }

    /// Base translation: Blockcerts Wallet
    public static var BlockcertsWallet : String = NSLocalizedString("BlockcertsWallet", comment: "")

    /// Base translation: Introduced on
    public static var IntroducedOn : String = NSLocalizedString("IntroducedOn", comment: "")

    /// Base translation: OK
    public static var OK : String = NSLocalizedString("OK", comment: "")

    /// Base translation: Be careful
    public static var DeleteCredentialAlertTitle : String = NSLocalizedString("DeleteCredentialAlertTitle", comment: "")

    /// Base translation: Invalid Credential
    public static var InvalidCredential : String = NSLocalizedString("InvalidCredential", comment: "")

    /// Base translation: Logs have been deleted from this device.
    public static var DeleteLogsSuccess : String = NSLocalizedString("DeleteLogsSuccess", comment: "")

    /// Base translation: Import from URL
    public static var ImportFromURL : String = NSLocalizedString("ImportFromURL", comment: "")

    /// Base translation: Issuer Contact Email
    public static var IssuerContactEmail : String = NSLocalizedString("IssuerContactEmail", comment: "")

    /// Base translation: We couldn't understand this Issuer's response. Please contact the Issuer.
    public static var IssuerResponseErrorJSON : String = NSLocalizedString("IssuerResponseErrorJSON", comment: "")

    /// Base translation: This is a sample certificate that cannot be verified. Real certificates will perform a live validation process.
    public static var SampleCredentialVerificationImpossible : String = NSLocalizedString("SampleCredentialVerificationImpossible", comment: "")

    /// Base translation: Okay
    public static var Okay : String = NSLocalizedString("Okay", comment: "")

    /// Base translation: Backup Passphrase
    public static var BackupPassphrase : String = NSLocalizedString("BackupPassphrase", comment: "")

    /// Base translation: Issuer
    public static var Issuer : String = NSLocalizedString("Issuer", comment: "")

    /// Base translation: Please check your network connection and try again.
    public static var ReachabilityAlertMessage : String = NSLocalizedString("ReachabilityAlertMessage", comment: "")

    /// Base translation: Authenticate to see your secure passphrase.
    public static var AuthenticateSeePassphrase : String = NSLocalizedString("AuthenticateSeePassphrase", comment: "")

    /// Base translation: Date Issued
    public static var DateIssued : String = NSLocalizedString("DateIssued", comment: "")

    /// Base translation: Failed to authenticate. Try again.
    public static var AuthenticationError : String = NSLocalizedString("AuthenticationError", comment: "")

    /// Base translation: Credential Name
    public static var CredentialName : String = NSLocalizedString("CredentialName", comment: "")

    /// Base translation: Add Issuer Failed
    public static var AddIssuerFailAlertTitle : String = NSLocalizedString("AddIssuerFailAlertTitle", comment: "")

    /// Base translation: Issuer responded, but it contained an invalid property named "%@"
    public static func IssuerInvalidProperty(_ value1 : String) -> String {
        return String(format: NSLocalizedString("IssuerInvalidProperty", comment: ""), value1)
    }

    /// Base translation: Delete
    public static var Delete : String = NSLocalizedString("Delete", comment: "")

    /// Base translation: About Passphrases
    public static var AboutPassphrases : String = NSLocalizedString("AboutPassphrases", comment: "")

    /// Base translation: Adding this issuer failed. Please try again
    public static var AddIssuerFailAlertMessage : String = NSLocalizedString("AddIssuerFailAlertMessage", comment: "")

    /// Base translation: Share Link
    public static var ShareLink : String = NSLocalizedString("ShareLink", comment: "")

    /// Base translation: We couldn't authenticate you to the issuer. Double-check your one-time code and try again.
    public static var IssuerAuthenticationError : String = NSLocalizedString("IssuerAuthenticationError", comment: "")

    /// Base translation: Success!
    public static var Success : String = NSLocalizedString("Success", comment: "")

    /// Base translation: Add an Issuer
    public static var AddIssuer : String = NSLocalizedString("AddIssuer", comment: "")

    /// Base translation: The request was aborted. Please try again.
    public static var RequestAborted : String = NSLocalizedString("RequestAborted", comment: "")

    /// Base translation: Please try to authenticate again to see your passphrase.
    public static var GenericAuthenticationError : String = NSLocalizedString("GenericAuthenticationError", comment: "")

    /// Base translation: It looks like local authentication is disabled for this app. Without it, showing your passphrase is insecure. Please enable local authentication for this app in Settings.
    public static var LocalAuthenticationDisabled : String = NSLocalizedString("LocalAuthenticationDisabled", comment: "")

    /// Base translation: No Network Connection
    public static var ReachabilityAlertTitle : String = NSLocalizedString("ReachabilityAlertTitle", comment: "")

    /// Base translation: Replace Passphrase
    public static var ReplacePassphrase : String = NSLocalizedString("ReplacePassphrase", comment: "")

    /// Base translation: Unable to save this passphrase.
    public static var PassphraseSaveFail : String = NSLocalizedString("PassphraseSaveFail", comment: "")

    /// Base translation: Couldn't share certificate.
    public static var ShareCredentialError : String = NSLocalizedString("ShareCredentialError", comment: "")

    /// Base translation: Something went wrong when deleting that certificate.
    public static var DeleteCredentialGenericError : String = NSLocalizedString("DeleteCredentialGenericError", comment: "")

    /// Base translation: Please go to the Settings for Blockcerts Wallet and enable Touch ID, Face ID, or a passcode to secure your passphrase and try again.
    public static var EnableAuthenticationPrompt : String = NSLocalizedString("EnableAuthenticationPrompt", comment: "")

    /// Base translation: Information
    public static var Information : String = NSLocalizedString("Information", comment: "")

    /// Base translation: Current Passphrase
    public static var CurrentPassphrase : String = NSLocalizedString("CurrentPassphrase", comment: "")

    /// Base translation: Privacy Policy
    public static var PrivacyPolicy : String = NSLocalizedString("PrivacyPolicy", comment: "")

    /// Base translation: Add Credential
    public static var AddCredential : String = NSLocalizedString("AddCredential", comment: "")

    /// Base translation: Done
    public static var Done : String = NSLocalizedString("Done", comment: "")

    /// Base translation: This is a low-security backup method. Do you want to continue?
    public static var EmailBackupWarning : String = NSLocalizedString("EmailBackupWarning", comment: "")

    /// Base translation: Delete Credential
    public static var DeleteCredential : String = NSLocalizedString("DeleteCredential", comment: "")

    /// Base translation: Issuer Info
    public static var IssuerInfo : String = NSLocalizedString("IssuerInfo", comment: "")

    /// Base translation: Show Passphrase
    public static var ShowPassphrase : String = NSLocalizedString("ShowPassphrase", comment: "")

    /// Base translation: Close
    public static var Close : String = NSLocalizedString("Close", comment: "")

    /// Base translation: Cancel
    public static var Cancel : String = NSLocalizedString("Cancel", comment: "")

    /// Base translation: Select at Least One to Continue
    public static var SelectOne : String = NSLocalizedString("SelectOne", comment: "")

    /// Base translation: Credential Info
    public static var CredentialInfo : String = NSLocalizedString("CredentialInfo", comment: "")

    /// Base translation: Welcome
    public static var Welcome : String = NSLocalizedString("Welcome", comment: "")

    /// Base translation: We couldn't find the logs on the device.
    public static var DeviceMissingLogs : String = NSLocalizedString("DeviceMissingLogs", comment: "")

    /// Base translation: Adding Credential
    public static var AddingCredential : String = NSLocalizedString("AddingCredential", comment: "")

    /// Base translation: No description provided.
    public static var IssuerMissingDescription : String = NSLocalizedString("IssuerMissingDescription", comment: "")

    /// Base translation: There was an error adding this issuer. This can happen when a single-use invitation link is clicked more than once. Please check with the issuer and request a new invitation, if necessary.
    public static var AddIssuerFailMessage : String = NSLocalizedString("AddIssuerFailMessage", comment: "")

    /// Base translation: Something went wrong preparing that file for sharing. Try again later.
    public static var ShareCredentialGenericError : String = NSLocalizedString("ShareCredentialGenericError", comment: "")

    /// Base translation: Issuer Name
    public static var IssuerName : String = NSLocalizedString("IssuerName", comment: "")

    /// Base translation: Protect Your Passphrase
    public static var ProtectYourPassphrase : String = NSLocalizedString("ProtectYourPassphrase", comment: "")

    /// Base translation: Never
    public static var Never : String = NSLocalizedString("Never", comment: "")

    /// Base translation: Blockcerts Backup
    public static var BlockcertsBackup : String = NSLocalizedString("BlockcertsBackup", comment: "")

    /// Base translation: Adding Issuer
    public static var AddingIssuer : String = NSLocalizedString("AddingIssuer", comment: "")

}